[package]
name = "ui-macros"
version = "0.1.0"
edition.workspace = true

[dependencies]
yew = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
