[package]
name = "orchestrator-http-project"
version = "0.1.0"
edition = "2024"

[dependencies]
warp = { workspace = true }
serde = { workspace = true }
orchestrator-app = { path = "../orchestrator-app" }
orchestrator-http-core = { path = "../orchestrator-http-core" }
orchestrator-ops-project = { path = "../orchestrator-ops-project" }
