[package]
name = "ui-scene"
version = "0.1.0"
edition.workspace = true

[dependencies]
ui-core = { workspace = true }
ui-macros = { workspace = true }
yew = { workspace = true }
wasm-bindgen = { workspace = true }
web-sys = { workspace = true }
