[package]
name = "ui-app"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { workspace = true }
wasm-bindgen = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ui-core = { path = "../ui-core" }
