[package]
name = "ui-api"
version = "0.1.0"
edition.workspace = true

[dependencies]
ui-core = { workspace = true }
gloo-net = { workspace = true }
serde_json = { workspace = true }
wasm-bindgen-futures = { workspace = true }
