[package]
name = "orchestrator-adapter-tts"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
reqwest = { workspace = true }
serde = { workspace = true }
orchestrator-ports-services = { path = "../orchestrator-ports-services" }
