[package]
name = "orchestrator-script"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
serde_json = { workspace = true }
orchestrator-app = { path = "../orchestrator-app" }
orchestrator-domain = { path = "../orchestrator-domain" }
orchestrator-ports-project = { path = "../orchestrator-ports-project" }
orchestrator-ports-scene = { path = "../orchestrator-ports-scene" }
orchestrator-ports-asset = { path = "../orchestrator-ports-asset" }
orchestrator-ports-services = { path = "../orchestrator-ports-services" }
