[package]
name = "orchestrator-http"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
warp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
orchestrator-app = { path = "../orchestrator-app" }
orchestrator-ops-project = { path = "../orchestrator-ops-project" }
orchestrator-ops-scene = { path = "../orchestrator-ops-scene" }
orchestrator-ops-asset = { path = "../orchestrator-ops-asset" }
orchestrator-avatar-service = { path = "../orchestrator-avatar-service" }
orchestrator-avatar-pipeline = { path = "../orchestrator-avatar-pipeline" }
orchestrator-script = { path = "../orchestrator-script" }
orchestrator-http-handlers = { path = "../orchestrator-http-handlers" }
