[workspace]
members = ["crates/ui-shell"]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
ui-app = { path = "../ui-app/crates/ui-app" }
yew = { version = "0.21", features = ["csr"] }
wasm-bindgen = "0.2"
