[workspace]
members = [
    "crates/orchestrator-http-core",
    "crates/orchestrator-http-health",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
anyhow = "1"
warp = "0.3"
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
